name: Rocket Surgery Book
favicon: null
layout_spectrum: 0.5582759473472834
typography_spectrum: 0.85117
title: 'The simple, fun guide to a better Business!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc019c'
    - '#212936'
    - '#60ff4b'
    - '#2bad00'
  brandStrength: 0.04924199893139303
  lightness: 0.0045084895100444555
  saturation: 0.17276284703984857
  rhythmicContrast: 0.8642183423507959
purpose: []
